# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/PID_Stable/Basys3_constraints.xdc

# IP: ip/c_addsub_3/c_addsub_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_3 || ORIG_REF_NAME==c_addsub_3} -quiet] -quiet
