# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/luisg/Desktop/Fall 2018/PIDcontroller_Verilog/PID_Stable/PID_Stable.srcs/sources_1/ip/mult_8bx1b/mult_8bx1b.xci
# IP: The module: 'mult_8bx1b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisg/Desktop/Fall 2018/PIDcontroller_Verilog/PID_Stable/PID_Stable.srcs/sources_1/ip/mult_8bx1b/mult_8bx1b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_8bx1b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/luisg/Desktop/Fall 2018/PIDcontroller_Verilog/PID_Stable/PID_Stable.srcs/sources_1/ip/mult_8bx1b/mult_8bx1b.xci
# IP: The module: 'mult_8bx1b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisg/Desktop/Fall 2018/PIDcontroller_Verilog/PID_Stable/PID_Stable.srcs/sources_1/ip/mult_8bx1b/mult_8bx1b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_8bx1b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
